version: '3'

services:

  dev-haproxy:
    hostname: dex-haproxy
    build:
      context: ./
      dockerfile: haproxy/Dockerfile
    environment:
      - RABBITMQ_DEFAULT_USER=dream 
      - RABBITMQ_DEFAULT_PASS=231510622abc
      - PATH=$PATH:/opt/rabbitmq/sbin:/usr/local/bin/:/bin
    ports:
      - 5670:5670
      - 35672:35672
      - 35674:35674
      - 9999:9999
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - dex-quantitative

  dev-mongo:
    hostname: dex-mongo
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=231510622abc
    volumes:
      - ./mongo/db:/data/db
      - ./mongo/configdb:/data/configdb
    ports:
      - 27017:27017
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - dex-quantitative

  dev-mongo-express:
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=dex-mongo
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=231510622abc
    ports:
      - 8081:8081
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - dex-quantitative

  dev-mysql:
    hostname: dex-mysql
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    volumes:
      - ./mysql/datadir:/var/lib/mysql
      - ./mysql/conf:/etc/mysql/conf.d
      - ./mysql/init:/docker-entrypoint-initdb.d
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - dex-quantitative

  dev-phpmyadmin:
    hostname: dex-phpmyadmin
    image: phpmyadmin
    restart: always
    ports:
      - 8888:80
    environment:
      - PMA_ARBITRARY=1
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - dex-quantitative

  dev-node:
    hostname: dex-node
    build:
      context: ./
      dockerfile: node-server/Dockerfile
    ports:
      - 8080:8080
      - 9527:9527
    volumes:
      - ./build:/opt/build
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - dex-quantitative

networks:
  dex-quantitative:
    driver:
      bridge